### PR TITLE
add basic linting

### PR DESCRIPTION
**Pull request by NickyMeuleman**
ref #3 
Added linting using [ESLint](https://eslint.org/)
Using the `ESLint:recommended` preset at the moment. The rules it includes have a checkmark next to them [in this list](https://eslint.org/docs/rules/)

To use: run `npm run lint` (or `yarn lint` if you are using `yarn`) in the project directory.

Would you like me to add automated code formatting/style enforcement (using [Prettier](https://prettier.io/)) as well?

### CODE REVIEW

**Comment by sagar-jadhav** [comment]
> Would you like me to add automated code formatting/style enforcement (using [Prettier](https://prettier.io/)) as well?

Sure go ahead 👍 

Thank you for contribution !!

**Comment by NickyMeuleman** [comment]
Added Prettier through ESLint, so there is no change in usage.

Added a tiny bit of configuration in the `.prettierrc` file to conform the style to the style the project already used.
Feel free to change this, [this docs page](https://prettier.io/docs/en/options.html) has a list of all their options.

**Comment by NickyMeuleman** [comment]
🚀 
Noticed the  `yarn.lock` was added.
Not a huge deal, but if you're using `npm`, remove it in favour of `package-lock.json`

**Comment by sagar-jadhav** [comment]
Removed `yarn.lock`

**Pull request merged**
